spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/covid_tracing?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 11111111
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    dbcp2:
      validation-query: SELECT 1


  rabbitmq:
    host: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    username: covid
    password: covid


  mail:
    host: smtp.gmail.com
    port: 587
    username: ejsvk3284@gmail.com
    password: 1q2w3e4r1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        mime:
          address:
            strict: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:covid.tracing.mappers/**/*.xml

server:
  port: 8888

logging:
  config: classpath:logback-spring.xml
  file:
    name: logfile.log
    path: ./logs/


#logging:
#  level:
#    jdbc.sqlonly: debug        # sql문 로깅
#    jdbc.sqltiming: debug      # sql 실행 시간 로깅
#    jdbc.resultsettable: debug # 쿼리 결과 테이블 형식으로 로깅
