spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid_tracing?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:covid.tracing.mappers/**/*.xml

server:
  port: 8888
