spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid_tracing?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1

  rabbitmq:
    host: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    username: covid
    password: covid

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false # 개발 모드 : false, 운영 모드 : true
    encoding: utf-8

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        mime:
          address:
            strict: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:covid.tracing.mappers/**/*.xml

server:
  port: 8888


